apiVersion: 1
datasources:
  - name: ShadowCheck-Postgres
    type: postgres
    url: 127.0.0.1:5432
    database: shadowcheck_db
    user: shadowcheck_user
    secureJsonData:
      password: "${DB_PASSWORD}"
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
