/**
 * Dashboard Card Definitions
 */

import React from 'react';
import type { CardData } from './MetricCard';

type DashboardIcon = React.FC<{ size?: number; className?: string; style?: React.CSSProperties }>;

// Icons will be provided by the parent component
export const createInitialCards = (icons: {
  Network: DashboardIcon;
  Wifi: DashboardIcon;
  Smartphone: DashboardIcon;
  Bluetooth: DashboardIcon;
  Tower: DashboardIcon;
  Radio: DashboardIcon;
  BarChart3: DashboardIcon;
  AlertTriangle: DashboardIcon;
}): CardData[] => [
  {
    id: 1,
    title: 'Total Networks',
    value: 0,
    icon: icons.Network,
    color: '#3b82f6',
    x: 0,
    y: 80,
    w: 33.33,
    h: 200,
    type: 'total-networks',
    observations: 0,
  },
  {
    id: 2,
    title: 'WiFi Networks',
    value: 0,
    icon: icons.Wifi,
    color: '#10b981',
    x: 33.33,
    y: 80,
    w: 33.33,
    h: 200,
    type: 'wifi-count',
    observations: 0,
  },
  {
    id: 3,
    title: 'BLE Devices',
    value: 0,
    icon: icons.Smartphone,
    color: '#8b5cf6',
    x: 66.66,
    y: 80,
    w: 33.33,
    h: 200,
    type: 'radio-ble',
    observations: 0,
  },
  {
    id: 4,
    title: 'Bluetooth Classic',
    value: 0,
    icon: icons.Bluetooth,
    color: '#06b6d4',
    x: 0,
    y: 290,
    w: 33.33,
    h: 200,
    type: 'radio-bt',
    observations: 0,
  },
  {
    id: 5,
    title: 'LTE Networks',
    value: 0,
    icon: icons.Tower,
    color: '#ec4899',
    x: 33.33,
    y: 290,
    w: 33.33,
    h: 200,
    type: 'radio-lte',
    observations: 0,
  },
  {
    id: 6,
    title: 'GSM Networks',
    value: 0,
    icon: icons.Radio,
    color: '#f59e0b',
    x: 66.66,
    y: 290,
    w: 33.33,
    h: 200,
    type: 'radio-gsm',
    observations: 0,
  },
  {
    id: 7,
    title: '5G NR Networks',
    value: 0,
    icon: icons.Tower,
    color: '#14b8a6',
    x: 0,
    y: 500,
    w: 33.33,
    h: 200,
    type: 'radio-nr',
    observations: 0,
  },
  {
    id: 8,
    title: 'Analytics Dashboard',
    value: '→',
    icon: icons.BarChart3,
    color: '#64748b',
    x: 33.33,
    y: 500,
    w: 33.33,
    h: 200,
    type: 'analytics-link',
    observations: 0,
  },
  {
    id: 9,
    title: 'Critical Threats',
    value: 0,
    icon: icons.AlertTriangle,
    color: '#ef4444',
    x: 66.66,
    y: 500,
    w: 33.33,
    h: 200,
    type: 'threat-critical',
    observations: 0,
  },
  {
    id: 10,
    title: 'High Threats',
    value: 0,
    icon: icons.AlertTriangle,
    color: '#f97316',
    x: 0,
    y: 710,
    w: 33.33,
    h: 200,
    type: 'threat-high',
    observations: 0,
  },
  {
    id: 11,
    title: 'Medium Threats',
    value: 0,
    icon: icons.AlertTriangle,
    color: '#eab308',
    x: 33.33,
    y: 710,
    w: 33.33,
    h: 200,
    type: 'threat-medium',
    observations: 0,
  },
  {
    id: 12,
    title: 'Low Threats',
    value: 0,
    icon: icons.AlertTriangle,
    color: '#22c55e',
    x: 66.66,
    y: 710,
    w: 33.33,
    h: 200,
    type: 'threat-low',
    observations: 0,
  },
];
