-- Migration: Add KML staging tables for recovery and reconciliation workflows
--
-- Purpose:
-- - Store lossy KML exports in source-native staging tables
-- - Preserve file provenance separately from parsed point rows
-- - Keep KML-derived data out of canonical observation tables until reviewed

-- --------------------------------------------------------------------------
-- kml_files
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app.kml_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file text NOT NULL,
    source_name text,
    source_type text NOT NULL DEFAULT 'kml',
    file_hash text,
    placemark_count integer NOT NULL DEFAULT 0,
    imported_at timestamp with time zone NOT NULL DEFAULT now(),
    raw_kml jsonb DEFAULT '{}'::jsonb
);

COMMENT ON TABLE app.kml_files IS
  'File-level staging metadata for imported KML/KMZ artifacts used in recovery and reconciliation workflows.';
COMMENT ON COLUMN app.kml_files.source_file IS
  'Original file path or filename used during import.';
COMMENT ON COLUMN app.kml_files.source_name IS
  'Document-level display name extracted from the KML when present.';
COMMENT ON COLUMN app.kml_files.source_type IS
  'Source family for the KML artifact, e.g. wigle.';
COMMENT ON COLUMN app.kml_files.file_hash IS
  'Optional content hash for deduplication and provenance checks.';
COMMENT ON COLUMN app.kml_files.raw_kml IS
  'Optional file-level raw metadata captured during parsing.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_kml_files_source_file
  ON app.kml_files (source_file);

CREATE UNIQUE INDEX IF NOT EXISTS idx_kml_files_file_hash
  ON app.kml_files (file_hash)
  WHERE file_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_kml_files_imported_at
  ON app.kml_files (imported_at DESC);


-- --------------------------------------------------------------------------
-- kml_points
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app.kml_points (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kml_file_id bigint NOT NULL,
    folder_name text,
    name text,
    network_id text,
    bssid text,
    encryption text,
    attributes text,
    observed_at timestamp with time zone,
    signal_dbm double precision,
    accuracy_m double precision,
    network_type text,
    location public.geometry(Point,4326),
    raw_description text,
    raw_kml jsonb DEFAULT '{}'::jsonb
);

COMMENT ON TABLE app.kml_points IS
  'Point-level KML staging rows parsed from Placemark entries. These rows are preserved as imported and are not canonical observations.';
COMMENT ON COLUMN app.kml_points.folder_name IS
  'Folder label from the source KML, e.g. Wifi Networks or Cellular Networks.';
COMMENT ON COLUMN app.kml_points.network_id IS
  'Identifier parsed from the KML description, usually from the Network ID field.';
COMMENT ON COLUMN app.kml_points.bssid IS
  'Normalized WiFi BSSID when the KML point type is WIFI; null for non-WiFi rows unless explicitly meaningful.';
COMMENT ON COLUMN app.kml_points.location IS
  'Geometry point from the KML coordinates in SRID 4326.';
COMMENT ON COLUMN app.kml_points.raw_description IS
  'Original KML Placemark description text before field parsing.';
COMMENT ON COLUMN app.kml_points.raw_kml IS
  'Optional raw parsed KML payload for debugging and future remapping.';

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'kml_points_kml_file_id_fkey') THEN
        ALTER TABLE ONLY app.kml_points
            ADD CONSTRAINT kml_points_kml_file_id_fkey
            FOREIGN KEY (kml_file_id) REFERENCES app.kml_files(id) ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_kml_points_kml_file_id
  ON app.kml_points (kml_file_id);

CREATE INDEX IF NOT EXISTS idx_kml_points_network_id
  ON app.kml_points (network_id)
  WHERE network_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_kml_points_bssid
  ON app.kml_points (bssid)
  WHERE bssid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_kml_points_observed_at
  ON app.kml_points (observed_at DESC)
  WHERE observed_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_kml_points_network_type
  ON app.kml_points (network_type)
  WHERE network_type IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_kml_points_location
  ON app.kml_points USING gist (location)
  WHERE location IS NOT NULL;


-- --------------------------------------------------------------------------
-- runtime permissions
-- --------------------------------------------------------------------------
GRANT SELECT ON TABLE app.kml_files TO shadowcheck_user;
GRANT SELECT ON TABLE app.kml_points TO shadowcheck_user;
GRANT USAGE ON SEQUENCE app.kml_files_id_seq TO shadowcheck_user;
GRANT USAGE ON SEQUENCE app.kml_points_id_seq TO shadowcheck_user;
