-- Migration: Add experimental anchor points table for high-confidence beacon validation
--
-- Purpose:
-- - Store curated stationary radio beacons used for validation and calibration workflows
-- - Support confidence scoring based on signal stability, geographic spread, and repeat observations
-- - Keep the dataset available for future productionization without blocking experimentation

CREATE TABLE IF NOT EXISTS app.anchor_points (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bssid text NOT NULL,
    ssid text,
    manufacturer text,
    location_label text NOT NULL,
    lat double precision NOT NULL,
    lon double precision NOT NULL,
    avg_signal double precision,
    signal_stddev double precision,
    geo_stddev_m double precision,
    observation_count integer,
    unique_days integer,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    confidence text DEFAULT 'medium'::text,
    wigle_confirmed boolean DEFAULT false,
    notes text,
    created_at timestamp with time zone DEFAULT now()
);

COMMENT ON TABLE app.anchor_points IS
  'Stationary radio beacons used for device location verification and signal calibration';

CREATE UNIQUE INDEX IF NOT EXISTS idx_anchor_points_bssid_location_label
  ON app.anchor_points (bssid, location_label);

CREATE INDEX IF NOT EXISTS idx_anchor_points_location_label
  ON app.anchor_points (location_label);

CREATE INDEX IF NOT EXISTS idx_anchor_points_bssid
  ON app.anchor_points (bssid);

GRANT SELECT ON TABLE app.anchor_points TO shadowcheck_user;
GRANT SELECT ON TABLE app.anchor_points TO grafana_reader;
GRANT USAGE, SELECT ON SEQUENCE app.anchor_points_id_seq TO shadowcheck_user;
GRANT USAGE ON SEQUENCE app.anchor_points_id_seq TO grafana_reader;
