export {};

import {
  addNetworkNote,
  checkDuplicateObservations,
  deleteNetworkTag,
  exportMLTrainingSet,
  getBackupData,
  getNetworkSummary,
  fetchNetworksPendingWigleLookup,
  insertNetworkTagIgnore,
  insertNetworkTagNotes,
  insertNetworkThreatTag,
  markNetworkInvestigate,
  requestWigleLookup,
  updateNetworkTagIgnore,
  updateNetworkTagNotes,
  updateNetworkThreatTag,
  upsertNetworkTag,
} from '../repositories/adminNetworkTagRepository';
import {
  addTagToNetwork,
  getAllNetworkTags,
  getMACRandomizationSuspects,
  getNetworkTagsAndNotes,
  getNetworkTagsByBssid,
  getNetworkTagsExpanded,
  getOUIGroupDetails,
  getOUIGroups,
  insertNetworkTagWithNotes,
  removeTagFromNetwork,
  searchNetworksByTag,
  searchNetworksByTagArray,
} from '../repositories/adminNetworkTagOuiRepository';

module.exports = {
  checkDuplicateObservations,
  addNetworkNote,
  getNetworkSummary,
  getBackupData,
  upsertNetworkTag,
  updateNetworkTagIgnore,
  insertNetworkTagIgnore,
  updateNetworkThreatTag,
  insertNetworkThreatTag,
  updateNetworkTagNotes,
  insertNetworkTagNotes,
  deleteNetworkTag,
  requestWigleLookup,
  markNetworkInvestigate,
  fetchNetworksPendingWigleLookup,
  exportMLTrainingSet,
  getOUIGroups,
  getOUIGroupDetails,
  getMACRandomizationSuspects,
  getNetworkTagsByBssid,
  getNetworkTagsAndNotes,
  getAllNetworkTags,
  searchNetworksByTag,
  insertNetworkTagWithNotes,
  removeTagFromNetwork,
  addTagToNetwork,
  getNetworkTagsExpanded,
  searchNetworksByTagArray,
};
