export {};

const {
  insertNetworkMedia,
  selectNetworkMediaList,
  selectNetworkMediaFile,
  selectNetworkMediaThumbnail,
  selectRelatedNetworkMediaForBssid,
  selectUnmatchedMediaPoints,
  selectMatchedMediaPoints,
  insertNetworkNotation,
  selectNetworkNotations,
  insertNetworkNote,
  selectNetworkNotes,
  softDeleteNetworkNote,
  updateNetworkNoteContent,
  selectNetworkNoteById,
  insertNoteMedia,
  selectNoteMediaById,
  selectNoteMediaList,
  deleteNoteMedia,
  deleteNetworkMedia,
  getDuplicateMediaGroups,
  checkDuplicateMedia,
} = require('../repositories/adminNetworkMediaRepository');

module.exports = {
  checkDuplicateMedia,
  uploadNetworkMedia: insertNetworkMedia,
  getNetworkMediaList: selectNetworkMediaList,
  getNetworkMediaFile: selectNetworkMediaFile,
  getNetworkMediaThumbnail: selectNetworkMediaThumbnail,
  getRelatedNetworkMediaForBssid: selectRelatedNetworkMediaForBssid,
  getUnmatchedMediaPoints: selectUnmatchedMediaPoints,
  getMatchedMediaPoints: selectMatchedMediaPoints,
  addNetworkNotation: insertNetworkNotation,
  getNetworkNotations: selectNetworkNotations,
  addNetworkNoteWithFunction: insertNetworkNote,
  getNetworkNotes: selectNetworkNotes,
  deleteNetworkNote: softDeleteNetworkNote,
  updateNetworkNote: updateNetworkNoteContent,
  getNetworkNoteById: selectNetworkNoteById,
  addNoteMedia: insertNoteMedia,
  getNoteMediaById: selectNoteMediaById,
  getNoteMediaList: selectNoteMediaList,
  deleteNoteMedia,
  deleteNetworkMedia,
  getDuplicateMediaGroups,
};
